name: snake
description: "A new Flutter project."
publish_to: "none"
version: 0.1.1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.22.0
  flame_bloc: ^1.12.4
  flutter_bloc: ^8.1.6
  equatable: ^2.0.7
  socket_io_client: ^3.0.2
  flame_audio: ^2.10.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/buttons/
    - assets/images/backgroung/
    - assets/images/animations/
    - assets/audio/
